// Seed content for Real Dutch Fluency. All examples target B1+ Flemish Dutch.
// Naturalness scores are out of 10 — the correct answer is the one a native
// 20-something in Belgium would actually say in that situation.

module.exports = {
  scenarios: [
    {
      category: 'University', level: 'B1', setting: 'Cafeteria, lunch break',
      prompt: 'Een medestudent: "Amai, die examens komen rap dichterbij hé. Hoe is\'t bij u?"',
      options: [
        "Het gaat zeer goed, dank u wel.",
        "'t Valt mee eigenlijk, ik heb al wa gestudeerd. En bij u?",
        "Ik ben bang van de examens.",
        "Ja, de examens zijn binnenkort.",
      ],
      correctIndex: 1,
      scores: [3, 9, 4, 2],
      explanation: "Optie B klinkt natuurlijk: 't Valt mee + eigenlijk + 'en bij u?' geeft de bal terug. A is veel te formeel voor een medestudent. C is grammaticaal ok maar emotioneel te zwaar voor small talk. D herhaalt gewoon wat de ander al zei.",
      alternatives: [
        "Bwa, 't gaat. Ik probeer er nie te veel aan te denken.",
        "Allee, 'k heb nog veel te doen maar 't komt wel goed zeker.",
      ],
    },
    {
      category: 'Friendships', level: 'B1', setting: 'Vriend belt vrijdagavond',
      prompt: 'Vriend: "Goesting om iets te gaan drinken vanavond?"',
      options: [
        "Ja ik heb goesting om iets te drinken.",
        "Tof! Waar spreken we af?",
        "Ik kan niet, ik moet studeren.",
        "Dat klinkt goed, ik zou graag komen.",
      ],
      correctIndex: 1,
      scores: [3, 10, 6, 4],
      explanation: "B is de natuurlijke Vlaamse respons: kort, enthousiast, en stuurt het gesprek meteen naar de praktische vraag. A klinkt als een vertaaloefening. C is prima als 't waar is, maar voor de oefening missen we energie. D is grammaticaal correct maar te formeel.",
      alternatives: [
        "Zeker, ik heb wel zin in een pintje. Hoe laat?",
        "Goesting genoeg, ja. Komt gij naar 't centrum of?",
      ],
    },
    {
      category: 'Internships', level: 'B2', setting: 'Stagebegeleider vraagt naar deadline',
      prompt: 'Begeleider: "Ga je da rapport tegen vrijdag rond krijgen, denkte?"',
      options: [
        "Ja, geen probleem.",
        "Ik zal mijn best doen.",
        "'t Zou moeten lukken, ja. Als er nog iets tussenkomt laat ik 't weten.",
        "Misschien, ik weet het niet zeker.",
      ],
      correctIndex: 2,
      scores: [5, 4, 9, 3],
      explanation: "C is professioneel-Vlaams: 't zou moeten lukken is voorzichtig maar positief, en je dekt jezelf in zonder onzeker te klinken. A is te kortaf. B is een rode vlag — klinkt alsof je het niet gaat halen. D laat de begeleider met angst zitten.",
      alternatives: [
        "Ja, da moet lukken. Ik ben bezig met't laatste deel.",
        "Vrijdag is krap, maar 'k denk van wel. 'k Hou u op de hoogte.",
      ],
    },
    {
      category: 'Dating', level: 'B2', setting: 'Na een eerste date, sms',
      prompt: 'Match: "Was echt een toffe avond gisteren 😊"',
      options: [
        "Ja, ik vond het ook leuk.",
        "Vond ik ook! Zin om volgende week iets te gaan eten?",
        "Bedankt voor de leuke avond.",
        "Het was inderdaad een aangename avond.",
      ],
      correctIndex: 1,
      scores: [5, 10, 4, 2],
      explanation: "B matcht de energie én zet meteen een volgende stap. Dat is wat Vlamingen doen wanneer ze interesse hebben — niet wachten, maar zelf voorstellen. A is veilig maar passief. C klinkt als na een sollicitatiegesprek. D is bijna komisch formeel.",
      alternatives: [
        "Echt wel! Wanneer past 't bij u voor een tweede ronde?",
        "Pff ja, gezellig hé. Doen we 't opnieuw?",
      ],
    },
    {
      category: 'Public transport', level: 'B1', setting: 'Trein vertraagd, conducteur',
      prompt: 'Conducteur: "Sorry mensen, we hebben hier een seinstoring, da gaat efkes duren."',
      options: [
        "Dat is niet acceptabel.",
        "Hoelang gaat het duren?",
        "Allee zeg, da valt tegen. Enig idee hoelang?",
        "Geen probleem hoor, ik heb tijd.",
      ],
      correctIndex: 2,
      scores: [1, 6, 9, 5],
      explanation: "C voelt 100% Vlaams: 'allee zeg' is mild gefrustreerd zonder agressief te zijn, 'da valt tegen' is de standaard understatement, en je vraagt info zonder de conducteur aan te vallen. A is een toerist-fout. B is correct maar koud. D is overdreven aardig.",
      alternatives: [
        "Bwa, 't is wat 't is. Weet ge al hoelang?",
        "Amai, just nu. Heb je een schatting?",
      ],
    },
    {
      category: 'Colleagues', level: 'B2', setting: 'Collega vraagt hulp net voor je weggaat',
      prompt: 'Collega: "Hé, hebt ge nog 5 minuutjes? \'k Geraak hier nie uit."',
      options: [
        "Nee, ik moet weg.",
        "Eigenlijk moet 'k weg, maar zeg \'s rap wat \'t is dan zien we.",
        "Sorry, geen tijd.",
        "Natuurlijk, geen probleem.",
      ],
      correctIndex: 1,
      scores: [3, 9, 4, 5],
      explanation: "B is de Vlaamse middenweg: je geeft eerlijk aan dat 't krap is ('eigenlijk' verzacht de boodschap), maar je laat de deur open. Dat is de toon die collega's onthouden. A en C branden goodwill op. D belooft te veel als je écht weg moet.",
      alternatives: [
        "'k Sta eigenlijk al recht, maar wa is\'t? Misschien kan 'k het rap zien.",
        "Efkes dan, ge moet \'t kort houden hé.",
      ],
    },
    {
      category: 'Shopping', level: 'B1', setting: 'Winkelbediende biedt hulp',
      prompt: 'Bediende: "Kan ik u ergens mee helpen?"',
      options: [
        "Nee dank u, ik kijk gewoon even rond.",
        "Nee, ik wil niets kopen.",
        "Ja, geef me een korting.",
        "Dank u, ik ben aan't kijken.",
      ],
      correctIndex: 3,
      scores: [7, 3, 1, 9],
      explanation: "D is exact wat Vlamingen zeggen in een winkel — 'aan't kijken' is de standaardformule. A is correct maar klinkt nét te boekjes-Nederlands. B is bot. C is een grap, geen antwoord.",
      alternatives: [
        "Merci, 'k kijk even rond.",
        "Nee \'t gaat wel, 'k kom u zeggen als 'k iets nodig heb.",
      ],
    },
    {
      category: 'Student life', level: 'B1', setting: 'Huisgenoot in de keuken',
      prompt: 'Huisgenoot: "Amai, jij ziet er moe uit. Lange dag gehad?"',
      options: [
        "Ja, ik ben heel moe geweest vandaag.",
        "Pff, vraag het mij niet. \'k Ben kapot.",
        "Het gaat wel, dank u.",
        "Misschien.",
      ],
      correctIndex: 1,
      scores: [4, 10, 4, 1],
      explanation: "B is exact hoe een student dat zegt: 'pff', 'vraag het mij niet', 'kapot'. Dat is de toon. A vertaalt het te letterlijk. C is te formeel met 'dank u' tegen een huisgenoot. D is geen antwoord.",
      alternatives: [
        "Bwa ja, 'k zie\'t niet meer zitten vandaag.",
        "Echt lange dag ja, 'k ga vroeg naar bed denk ik.",
      ],
    },
    {
      category: 'Sports', level: 'B2', setting: 'Na een verloren wedstrijd',
      prompt: 'Teamgenoot: "Bah, dat was geen goeie match van ons hé."',
      options: [
        "Wij hebben slecht gespeeld.",
        "Nee echt nie, maar volgende keer pakken we ze.",
        "Het is jammer.",
        "We hebben verloren omdat we niet goed waren.",
      ],
      correctIndex: 1,
      scores: [4, 10, 3, 2],
      explanation: "B is dé teamtoon: bevestigen + meteen vooruit kijken. 'pakken we ze' is fysiek/strijdbaar Vlaams. A is grammaticaal correct maar zonder vuur. C is te zacht. D analyseert in plaats van te reageren.",
      alternatives: [
        "Da was nie ons dag, ma volgende week is\'t weer iets anders.",
        "Allee, kop op. We trainen er op door.",
      ],
    },
    {
      category: 'Belgian daily life', level: 'B2', setting: 'Buur over het weer',
      prompt: 'Buur: "Tis weeral aan\'t regenen zeker."',
      options: [
        "Ja, het regent inderdaad.",
        "Tja, België hé.",
        "Het is slecht weer.",
        "Ja, het is heel nat.",
      ],
      correctIndex: 1,
      scores: [4, 10, 3, 3],
      explanation: "B is hét antwoord. Korte berusting, gedeelde identiteit, niets meer nodig. A herhaalt enkel. C en D voegen niets toe. 'België hé' is een complete zin in Vlaanderen.",
      alternatives: [
        "Bwa, wat hadde gij verwacht zeker.",
        "'t Is nie anders.",
      ],
    },
  ],

  hiddenMeaning: [
    {
      phrase: "'t Is wel oké.",
      surfaceMeaning: "Het is goed.",
      hiddenMeaning: "Het is eigenlijk niet zo goed — milde teleurstelling of beleefdheid.",
      emotionalContext: "Lauw, voorzichtig kritisch.",
      interpretations: [
        "Echt goed, geen problemen.",
        "Niet slecht, maar ook niet wat ik gehoopt had.",
        "Verschrikkelijk, maar ik wil niet klagen.",
        "Perfect, ik ben enthousiast.",
      ],
      correctIndex: 1,
    },
    {
      phrase: "We zien wel hé.",
      surfaceMeaning: "We zullen zien.",
      hiddenMeaning: "Ik wil er nu niet over praten / ik geloof er niet echt in.",
      emotionalContext: "Vermijdend, soms licht sceptisch.",
      interpretations: [
        "Ik ben er zeker van.",
        "Ik wil het gesprek nu afsluiten.",
        "Ik wacht enthousiast op het resultaat.",
        "Ik weet het exacte antwoord later.",
      ],
      correctIndex: 1,
    },
    {
      phrase: "Da's straf.",
      surfaceMeaning: "Dat is sterk.",
      hiddenMeaning: "Dat is indrukwekkend OF schokkend — afhankelijk van toon.",
      emotionalContext: "Verbazing, vaak met ondertoon van ongeloof.",
      interpretations: [
        "Letterlijk: dat is fysiek sterk.",
        "Wow, dat is echt opmerkelijk.",
        "Dat is normaal.",
        "Dat is grappig.",
      ],
      correctIndex: 1,
    },
    {
      phrase: "Ja ja.",
      surfaceMeaning: "Ja, ik begrijp het.",
      hiddenMeaning: "Ik geloof u niet / ik luister niet echt.",
      emotionalContext: "Sceptisch tot afwijzend.",
      interpretations: [
        "Volledige instemming.",
        "Ik geloof er geen woord van.",
        "Ik vraag verduidelijking.",
        "Ik ben enthousiast akkoord.",
      ],
      correctIndex: 1,
    },
    {
      phrase: "'k Zal\'s zien.",
      surfaceMeaning: "Ik ga kijken.",
      hiddenMeaning: "Waarschijnlijk niet — beleefde afwijzing.",
      emotionalContext: "Vrijblijvend, eerder nee dan ja.",
      interpretations: [
        "Ik kom zeker.",
        "Reken er niet op.",
        "Ik vraag het aan iemand anders.",
        "Ik twijfel echt 50/50.",
      ],
      correctIndex: 1,
    },
    {
      phrase: "Ge moet da nie doen hoor.",
      surfaceMeaning: "Je moet dat niet doen.",
      hiddenMeaning: "Wat je deed was lief — verzwakte dankbaarheid.",
      emotionalContext: "Geroerd, maar te bescheiden om dat openlijk te zeggen.",
      interpretations: [
        "Verbod — niet doen.",
        "Bedankt, dat was niet nodig maar lief.",
        "Onverschilligheid.",
        "Geïrriteerd.",
      ],
      correctIndex: 1,
    },
    {
      phrase: "'t Zal wel.",
      surfaceMeaning: "Het zal zo zijn.",
      hiddenMeaning: "Ik geloof het niet, maar 'k heb geen zin om te discussiëren.",
      emotionalContext: "Berustend-sarcastisch.",
      interpretations: [
        "Volle overtuiging.",
        "Sceptische berusting.",
        "Vraag om bewijs.",
        "Vrolijk akkoord.",
      ],
      correctIndex: 1,
    },
    {
      phrase: "Da valt tegen.",
      surfaceMeaning: "Dat valt mee niet.",
      hiddenMeaning: "Mild teleurgesteld, vaak understatement voor 'echt slecht'.",
      emotionalContext: "Understatement, typisch Vlaams.",
      interpretations: [
        "Beter dan verwacht.",
        "Slechter dan verwacht.",
        "Precies wat ik verwachtte.",
        "Geen mening.",
      ],
      correctIndex: 1,
    },
    {
      phrase: "Ja, eigenlijk wel.",
      surfaceMeaning: "Ja, in feite.",
      hiddenMeaning: "Ja, maar ik had het zelf niet zo verwoord — milde instemming met voorbehoud.",
      emotionalContext: "Nadenkend, half-akkoord.",
      interpretations: [
        "Volmondig ja.",
        "Akkoord met nuance.",
        "Volmondig nee.",
        "Geen mening.",
      ],
      correctIndex: 1,
    },
    {
      phrase: "'t Is nen echte hé.",
      surfaceMeaning: "Het is een echte.",
      hiddenMeaning: "Die persoon doet weer typisch zichzelf — soms positief, vaak licht spottend.",
      emotionalContext: "Vertederd of plagend.",
      interpretations: [
        "Letterlijk authentiek product.",
        "Typische karaktertrek, met knipoog.",
        "Onbekende persoon.",
        "Compliment over uiterlijk.",
      ],
      correctIndex: 1,
    },
  ],

  fastPrompts: [
    { prompt: "Hoe is\'t?",              casual: "Goe, en met u?",                friendly: "Bwa, 't gaat wel. En bij u?",        confident: "Top, druk maar fijn. Zelf?" },
    { prompt: "Waar zijde gisteren?",     casual: "Thuis, niks gedaan.",          friendly: "Bij vrienden, gezellig.",            confident: "Op een feestje, da was wel iets." },
    { prompt: "Goesting in een pintje?",  casual: "Altijd.",                       friendly: "Ja zeker, waar?",                    confident: "Doen we. 'k Trakteer de eerste." },
    { prompt: "Hoe was\'t examen?",       casual: "'t Viel mee.",                  friendly: "Bwa, redelijk. Ik denk dat 't ok is.", confident: "Zeer goed eigenlijk, 'k ben tevreden." },
    { prompt: "Wanneer komde langs?",     casual: "Weet ik nog niet.",             friendly: "'k Laat 't u rap weten.",            confident: "Zaterdag, past da bij u?" },
    { prompt: "Wat ga je dit weekend doen?", casual: "Niks speciaals.",            friendly: "Iets met vrienden waarschijnlijk.",  confident: "Festival zaterdag, zondag chillen." },
    { prompt: "Heb je honger?",           casual: "Bwa, gaat nog.",                friendly: "Ja eigenlijk wel, gij?",             confident: "Zeker, laat ons iets bestellen." },
    { prompt: "Komt da goed met die deadline?", casual: "'k Hoop't.",             friendly: "'k Denk van wel, ja.",               confident: "Ja, 'k heb 't onder controle." },
    { prompt: "Ge ziet er moe uit.",      casual: "'k Ben\'t ook.",                friendly: "Pff, lange week gehad.",             confident: "Klopt, maar 't is\'t waard geweest." },
    { prompt: "Hoe vondde de film?",      casual: "Wel oké.",                      friendly: "Tof eigenlijk, beter dan verwacht.", confident: "Echt straf, einde was geweldig." },
  ],

  sentenceBuilder: [
    {
      targetMeaning: "I really feel like going out tonight.",
      tokens: ["Ik", "heb", "echt", "goesting", "om", "vanavond", "uit", "te", "gaan"],
      correct: ["Ik", "heb", "echt", "goesting", "om", "vanavond", "uit", "te", "gaan"],
      alternatives: [
        ["'k", "Heb", "echt", "zin", "om", "vanavond", "uit", "te", "gaan"],
      ],
      explanation: "'Goesting hebben om + te + inf' is dé Vlaamse constructie. In NL zou 'zin' standaard zijn; in Vlaanderen klinkt 'goesting' natuurlijker.",
    },
    {
      targetMeaning: "It'll work out, don't worry.",
      tokens: ["Da", "komt", "wel", "goed", "hoor", "maak", "u", "geen", "zorgen"],
      correct: ["Da", "komt", "wel", "goed", "hoor"],
      alternatives: [
        ["Maak", "u", "geen", "zorgen", "da", "komt", "wel", "goed"],
      ],
      explanation: "'Hoor' is de zachte geruststellende deeltje. 'Maak u geen zorgen' is ook ok maar formeler.",
    },
    {
      targetMeaning: "I can't really see myself doing that.",
      tokens: ["Ik", "zie", "het", "niet", "echt", "zitten"],
      correct: ["Ik", "zie", "het", "niet", "echt", "zitten"],
      alternatives: [
        ["'t", "Zit", "er", "voor", "mij", "niet", "in"],
      ],
      explanation: "'Het zien zitten' = je voorstellen dat iets gaat lukken / er zin in hebben. Hyper-Vlaamse uitdrukking.",
    },
    {
      targetMeaning: "Let me think about it for a second.",
      tokens: ["Laat", "mij", "er", "efkes", "over", "nadenken"],
      correct: ["Laat", "mij", "er", "efkes", "over", "nadenken"],
      alternatives: [
        ["'k", "Moet", "er", "efkes", "over", "nadenken"],
      ],
      explanation: "'Efkes' = even, korte tijd. Markant Vlaams ipv 'eventjes'.",
    },
    {
      targetMeaning: "That's actually not bad at all.",
      tokens: ["Da's", "eigenlijk", "nog", "nie", "slecht"],
      correct: ["Da's", "eigenlijk", "nog", "nie", "slecht"],
      alternatives: [
        ["Eigenlijk", "valt", "da", "wel", "mee"],
      ],
      explanation: "Klassieke Vlaamse understatement-formule: 'eigenlijk nog niet slecht' = 'pretty good actually'.",
    },
  ],

  speechDecoder: [
    {
      textbook: "Wat ben je aan het doen?",
      realFlemish: "Wa zijde aant doen?",
      pronunciation: "[ˈʋɑ zɛi.də ɑnt ˈduː.ə]",
      contractions: "Wat→Wa, ben je→zijde, aan het→aant",
      regionalNote: "Algemeen Vlaams. 'Zijde' is de Vlaamse 2e persoon ('ben jij'). In West-Vlaanderen klinkt 't soms als 'Wuk zij'der aan 't doen'.",
    },
    {
      textbook: "Ik weet het niet.",
      realFlemish: "'k Weet 't nie.",
      pronunciation: "[k‿ʋeːt ət ni]",
      contractions: "Ik→'k, het→'t, niet→nie",
      regionalNote: "De 't' van 'niet' valt bijna altijd weg in spreektaal. 'k Wete\'t nie' hoor je ook (Antwerpen).",
    },
    {
      textbook: "Heb je dat gezien?",
      realFlemish: "Hedde da gezien?",
      pronunciation: "[ˈɦɛ.də dɑ ɣəˈzin]",
      contractions: "Heb je→hedde, dat→da",
      regionalNote: "'Hedde' is de samengetrokken vorm. Klinkt informeel en is universeel in Vlaanderen.",
    },
    {
      textbook: "Ga je nog mee?",
      realFlemish: "Gade nog mee?",
      pronunciation: "[ˈɣɑ.də nɔx meː]",
      contractions: "Ga je→gade",
      regionalNote: "'Gade', 'zijde', 'hedde' — het '-de' suffix vervangt 'je' bij vraagvormen. Geleerde regel: leer de drie samen.",
    },
    {
      textbook: "Ik heb daar geen zin in.",
      realFlemish: "'k Hè doa gin goesting in.",
      pronunciation: "[k‿ɦɛ doː xɪn ˈɣuː.stɪŋ ɪn]",
      contractions: "ik heb→'k hè, daar→doa, geen zin→gin goesting",
      regionalNote: "'Goesting' vervangt 'zin' bijna systematisch in spreektaal. 'Doa' is West/Oost-Vlaams; in Antwerpen blijft 't 'daar'.",
    },
    {
      textbook: "Wij gaan vanavond uit.",
      realFlemish: "Wij goan vanavond uit.",
      pronunciation: "[ʋɛi ɣoːn vəˈnɑ.vɔnt œyt]",
      contractions: "gaan→goan (regionaal)",
      regionalNote: "'Goan' is West-Vlaams. In Brabant/Antwerpen blijft 't 'gaan'. Goed te herkennen, niet noodzakelijk te imiteren.",
    },
    {
      textbook: "Dat is heel mooi.",
      realFlemish: "Da's echt schoon.",
      pronunciation: "[ˈdɑs ɛxt sxoːn]",
      contractions: "Dat is→Da's, heel→echt, mooi→schoon",
      regionalNote: "'Schoon' = mooi in Vlaanderen (in NL betekent 't enkel 'proper'). 'Echt' vervangt 'heel' als versterker.",
    },
    {
      textbook: "Even wachten alstublieft.",
      realFlemish: "Efkes wachten he.",
      pronunciation: "[ˈɛf.kəs ˈʋɑx.tə ɦeː]",
      contractions: "Even→efkes, alstublieft→he",
      regionalNote: "'He' op 't einde is geen vraag, maar een sociale lijm. Vervangt vaak 'alstublieft' in informele context.",
    },
  ],

  vocabulary: [
    { word: "amai",        meaning: "wow / oh wow",                level: "B1", example: "Amai, da was straf!",                       context: "uitroep van verbazing",       kind: "flemish" },
    { word: "allee",       meaning: "kom, well, anyway",            level: "B1", example: "Allee, doen we 't dan maar.",               context: "overgang / aansporing",       kind: "flemish" },
    { word: "goesting",    meaning: "zin / appetite",               level: "B1", example: "'k Heb goesting in een pintje.",            context: "verlangen, honger, zin",      kind: "flemish" },
    { word: "tof",         meaning: "leuk / cool",                  level: "B1", example: "Tof dat ge er zijt!",                       context: "positieve waardering",         kind: "flemish" },
    { word: "efkes",       meaning: "even / eventjes",              level: "B1", example: "Wacht efkes hé.",                            context: "kort moment",                  kind: "flemish" },
    { word: "chance",      meaning: "geluk",                        level: "B1", example: "'k Heb chance gehad met die trein.",       context: "geluk, mazzel",                kind: "flemish" },
    { word: "straf",       meaning: "indrukwekkend / heftig",       level: "B2", example: "Straf wa ge gedaan hebt.",                  context: "compliment of verbazing",      kind: "flemish" },
    { word: "precies",     meaning: "alsof / blijkbaar",            level: "B2", example: "Precies dat ge moe zijt.",                  context: "indruk uitdrukken",            kind: "flemish" },
    { word: "gezellig",    meaning: "cozy / pleasant",              level: "B1", example: "Was echt gezellig gisteren.",               context: "sfeer beschrijven",            kind: "general" },
    { word: "da valt tegen", meaning: "that's disappointing",       level: "B2", example: "De koffie hier? Da valt tegen.",            context: "milde teleurstelling",         kind: "flemish" },
    { word: "ik zie\'t niet zitten", meaning: "I'm not up for it",  level: "B2", example: "Sporten vandaag? 'k Zie\'t niet zitten.", context: "afwijzing met emotie",         kind: "flemish" },
    { word: "bwa",         meaning: "meh / well",                   level: "B1", example: "Bwa, 't gaat.",                              context: "lauwe respons",                kind: "slang" },
    { word: "kapot",       meaning: "uitgeput",                     level: "B1", example: "Na die training ben \'k kapot.",            context: "fysiek/mentaal uitgeput",      kind: "slang" },
    { word: "trakteren",   meaning: "to treat (someone)",           level: "B1", example: "Ik trakteer de eerste ronde.",              context: "sociaal gebaar in café",       kind: "general" },
    { word: "babbelen",    meaning: "kletsen",                      level: "B1", example: "We gaan nog efkes babbelen.",               context: "informeel praten",             kind: "flemish" },
  ],
};
